/// break.h

/* ported 7/11/96 DS minimal mods, */
/* Ported to H8S2623 - 01/03/99 (DTH) - No modifications */
// Ported to 2633 1/10/01 DGL -- No mods

#define TRAPA	0x5700
                     
/* where are these used? */                     
                     
#define BP_EQUAL		1
#define BP_LESS            	2
#define BP_GREATER         	3
#define BP_NOT_EQUAL       	4
#define BP_LESS_EQUAL      	5
#define BP_GREATER_EQUAL   	6
#define BP_BETWEEN			7

                   
/* where are these used? */
                   
#define BP_MEMORY 1
#define BP_COUNT 2
#define BP_REGISTER 3



