#####################################################
# MAKE file generated by HEW Version 1.1a (release 3)
#
# Details:
#   Project: IOCHeader
#   Configuration: Release
#   Toolchain: Hitachi H8S,H8/300 Standard Toolchain
#
#####################################################

##############################
# Toolchain directory Variable
# If incorrect, change to the location of the Hitachi H8S,H8/300 Standard Toolchain toolchain

TC_INSTALL_DIR = c:\hew\tools\hitachi\h8\3_0a_0

################
# Main Variables

# Hitachi H8S,H8/300 C/C++ Compiler phase

HITACHI_H8SH8300_CC_COMPILER_EXE=ch38.exe
HITACHI_H8SH8300_CC_COMPILER_EXEDIR=$(TC_INSTALL_DIR)\bin
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0="..\release\header.obj" 
HITACHI_H8SH8300_CC_COMPILER_DEPFILESC0="..\..\iocmain\include\version.h" "..\..\iocmain\include\constdef.h" \
	"..\..\iocmain\include\codeopt.h" 

# Hitachi H8S,H8/300 Assembler phase

HITACHI_H8SH8300_ASSEMBLER_EXE=asm38.exe

# Hitachi H8S,H8/300 IM OptLinker phase

HITACHI_H8SH8300_IM_OPTLINKER_EXE=optlnk38.exe
HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0="..\release\iocheader.abs" 

# Hitachi H Series Stype Converter phase

HITACHI_H_SERIES_STYPE_CONVERTER_EXE=cnvs.exe
HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0="..\release\iocheader.mot" 

#######################
# nmake "all" statement

all:	HITACHI_H8SH8300_CC_COMPILER_ENVC0 \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0) \
	$(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0) \
	$(HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Hitachi H8S,H8/300 C/C++ Compiler phase
!MESSAGE

HITACHI_H8SH8300_CC_COMPILER_ENVC0 : 
	set CH38TMP=C:\DOCUME~1\XPDEV~1\LOCALS~1\Temp
	set PATH=$(TC_INSTALL_DIR)\bin
	set CH38=$(TC_INSTALL_DIR)\include

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0) : "..\header.c"  $(HITACHI_H8SH8300_CC_COMPILER_DEPFILESC0)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\..\iocmain\include"
-object="..\release\header.obj"
-nolist
-chgincpath
"..\header.c"
-lang=c
<<

!MESSAGE
!MESSAGE Executing Hitachi H8S,H8/300 IM OptLinker phase
!MESSAGE

$(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0) : $(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_IM_OPTLINKER_EXE) -ws=<<
print "..\release\IOCHeader.map"
nooptimize
start CHeadSec(0210000),CHead1(0210200),CHead2(0210400),CHead3(0210600),CHead4(0210800),CHead5(0210A00)
exclude
udfcheck
check_section
align_section
output "..\release\IOCHeader.abs"
input "..\release\header.obj"
library "$(TC_INSTALL_DIR)\lib\c8s26n.lib"
library "$(TC_INSTALL_DIR)\lib\ec226n.lib"
exit
<<

!MESSAGE
!MESSAGE Executing Hitachi H Series Stype Converter phase
!MESSAGE

$(HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0) : $(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H_SERIES_STYPE_CONVERTER_EXE) -ws=<<
"..\release\IOCHeader.abs"
"..\release\IOCHeader.mot"
<<

