#####################################################
# MAKE file generated by HEW Version 1.1a (release 3)
#
# Details:
#   Project: Boot
#   Configuration: Release
#   Toolchain: Hitachi H8S,H8/300 Standard Toolchain
#
#####################################################

##############################
# Toolchain directory Variable
# If incorrect, change to the location of the Hitachi H8S,H8/300 Standard Toolchain toolchain

TC_INSTALL_DIR = c:\hew\tools\hitachi\h8\3_0a_0

################
# Main Variables

# Hitachi H8S,H8/300 C/C++ Compiler phase

HITACHI_H8SH8300_CC_COMPILER_EXE=ch38.exe
HITACHI_H8SH8300_CC_COMPILER_EXEDIR=$(TC_INSTALL_DIR)\bin
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0="..\release\hwsetup.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC1="..\release\intprg.src" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC2="..\release\resetprg.src" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC3="..\release\sbrk.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC4="..\release\dbsct.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC5="..\release\g_cmx.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC6="..\release\resource.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC7="..\release\cstart.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC8="..\release\cmx_init.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC9="..\release\asm.src" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC10="..\release\baseprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_DEPFILESC10="..\cmx\cxfuncs.h" "$(TC_INSTALL_DIR)\include\string.h" "..\cmxwrap\baseprocess.h" "..\include\datatype.h" \
	"..\include\constdef.h" "..\cmx\cxconfig.h" "..\global\g_cmx.h" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC11="..\release\queue.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC12="..\release\rtc.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC13="..\release\sci.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC14="..\release\timer.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC15="..\release\boot.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC16="..\release\vecttbl.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC17="..\release\ram_vect.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC18="..\release\debug.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC19="..\release\debugprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC20="..\release\allprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC21="..\release\userprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC22="..\release\debugdl.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC23="..\release\btmondl.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC24="..\release\ymodemrecv.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC25="..\release\storage.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC26="..\release\version.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC27="..\release\loader.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC28="..\release\dtc_vector.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC29="..\release\msghndl.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC30="..\release\branch.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC31="..\release\break.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC32="..\release\control.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC33="..\release\exe.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC34="..\release\ilreslv1.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC35="..\release\ilreslv2.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC36="..\release\ilreslv3.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC37="..\release\ilreslv4.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC38="..\release\init.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC39="..\release\instleng.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC40="..\release\main.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC41="..\release\bptable.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC42="..\release\sci_mon.obj" 
HITACHI_H8SH8300_CC_COMPILER_DEPFILESC42="..\monitor\extern.h" "..\monitor\mon_type.h" "..\monitor\sci_mon.h" "..\monitor\2623regs.h" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC43="..\release\ptpprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC44="..\release\ptplink.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC45="..\release\ptpisr.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC46="..\release\intqueue.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC47="..\release\memblock.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC48="..\release\memblocklist.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC49="..\release\memheap.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC50="..\release\crc16.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC51="..\release\dtcsci.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC52="..\release\ptpdnldsend.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC53="..\release\ptpdnldrecv.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC54="..\release\ptpdnldprocess.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC55="..\release\mailbox.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC56="..\release\amd29dl161db.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC57="..\release\amd29b16.obj" 
HITACHI_H8SH8300_CC_COMPILER_OUTFILESC58="..\release\watchdog.obj" 

# Hitachi H8S,H8/300 Assembler phase

HITACHI_H8SH8300_ASSEMBLER_EXE=asm38.exe
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC0="..\release\cxsk5ha.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC1="..\release\starth8s.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC2="..\release\execute.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC3="..\release\initshv.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC4="..\release\cstartup.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC5="..\release\intv.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC6="..\release\dtc.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC7="..\release\intprg.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC8="..\release\resetprg.obj" 
HITACHI_H8SH8300_ASSEMBLER_OUTFILESC9="..\release\asm.obj" 

# Hitachi H8S,H8/300 IM OptLinker phase

HITACHI_H8SH8300_IM_OPTLINKER_EXE=optlnk38.exe
HITACHI_H8SH8300_IM_OPTLINKER_INFILESC0="..\release\cxsk5ha.obj" "..\release\starth8s.obj" "..\release\execute.obj" "..\release\initshv.obj" \
	"..\release\cstartup.obj" "..\release\intv.obj" "..\release\dtc.obj" "..\release\intprg.obj" \
	"..\release\resetprg.obj" "..\release\asm.obj" "..\release\hwsetup.obj" "..\release\sbrk.obj" \
	"..\release\dbsct.obj" "..\release\g_cmx.obj" "..\release\resource.obj" "..\release\cstart.obj" \
	"..\release\cmx_init.obj" "..\release\baseprocess.obj" "..\release\queue.obj" "..\release\rtc.obj" \
	"..\release\sci.obj" "..\release\timer.obj" "..\release\boot.obj" "..\release\vecttbl.obj" \
	"..\release\ram_vect.obj" "..\release\debug.obj" "..\release\debugprocess.obj" "..\release\allprocess.obj" \
	"..\release\userprocess.obj" "..\release\debugdl.obj" "..\release\btmondl.obj" "..\release\ymodemrecv.obj" \
	"..\release\storage.obj" "..\release\version.obj" "..\release\loader.obj" "..\release\dtc_vector.obj" \
	"..\release\msghndl.obj" "..\release\branch.obj" "..\release\break.obj" "..\release\control.obj" \
	"..\release\exe.obj" "..\release\ilreslv1.obj" "..\release\ilreslv2.obj" "..\release\ilreslv3.obj" \
	"..\release\ilreslv4.obj" "..\release\init.obj" "..\release\instleng.obj" "..\release\main.obj" \
	"..\release\bptable.obj" "..\release\sci_mon.obj" "..\release\ptpprocess.obj" "..\release\ptplink.obj" \
	"..\release\ptpisr.obj" "..\release\intqueue.obj" "..\release\memblock.obj" "..\release\memblocklist.obj" \
	"..\release\memheap.obj" "..\release\crc16.obj" "..\release\dtcsci.obj" "..\release\ptpdnldsend.obj" \
	"..\release\ptpdnldrecv.obj" "..\release\ptpdnldprocess.obj" "..\release\mailbox.obj" "..\release\amd29dl161db.obj" \
	"..\release\amd29b16.obj" "..\release\watchdog.obj" 
HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0="..\release\boot.abs" 

# Hitachi H Series Stype Converter phase

HITACHI_H_SERIES_STYPE_CONVERTER_EXE=cnvs.exe
HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0="..\release\boot.mot" 

#######################
# nmake "all" statement

all:	HITACHI_H8SH8300_CC_COMPILER_ENVC0 \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC1) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC2) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC3) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC4) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC5) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC6) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC7) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC8) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC9) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC10) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC11) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC12) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC13) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC14) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC15) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC16) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC17) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC18) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC19) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC20) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC21) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC22) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC23) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC24) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC25) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC26) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC27) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC28) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC29) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC30) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC31) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC32) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC33) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC34) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC35) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC36) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC37) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC38) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC39) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC40) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC41) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC42) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC43) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC44) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC45) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC46) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC47) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC48) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC49) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC50) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC51) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC52) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC53) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC54) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC55) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC56) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC57) \
	$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC58) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC0) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC1) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC2) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC3) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC4) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC5) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC6) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC7) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC8) \
	$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC9) \
	$(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0) \
	$(HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Hitachi H8S,H8/300 C/C++ Compiler phase
!MESSAGE

HITACHI_H8SH8300_CC_COMPILER_ENVC0 : 
	set CH38TMP=C:\DOCUME~1\XPDEV~1\LOCALS~1\Temp
	set PATH=$(TC_INSTALL_DIR)\bin
	set CH38=$(TC_INSTALL_DIR)\include

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC0) : "..\h2633f\hwsetup.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\hwsetup.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\h2633f\hwsetup.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC1) : "..\h2633f\intprg.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-code=asmcode
-object="..\release\intprg.src"
-nolist
-chgincpath
"..\h2633f\intprg.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC2) : "..\h2633f\resetprg.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-code=asmcode
-object="..\release\resetprg.src"
-nolist
-chgincpath
"..\h2633f\resetprg.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC3) : "..\h2633f\sbrk.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\sbrk.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\h2633f\sbrk.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC4) : "..\h2633f\dbsct.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\dbsct.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\h2633f\dbsct.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC5) : "..\global\g_cmx.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\g_cmx.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\global\g_cmx.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC6) : "..\cmx\resource.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\resource.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmx\resource.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC7) : "..\cmx\cstart.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\cstart.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmx\cstart.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC8) : "..\cmx\cmx_init.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\cmx_init.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmx\cmx_init.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC9) : "..\cmxwrap\asm.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-code=asmcode
-object="..\release\asm.src"
-nolist
-chgincpath
"..\cmxwrap\asm.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC10) : "..\cmxwrap\baseprocess.cpp"  $(HITACHI_H8SH8300_CC_COMPILER_DEPFILESC10)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\baseprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\baseprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC11) : "..\cmxwrap\queue.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\queue.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\queue.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC12) : "..\cmxwrap\rtc.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\rtc.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\rtc.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC13) : "..\serial\sci.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\sci.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\sci.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC14) : "..\serial\timer.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\timer.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\timer.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC15) : "..\app\boot.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\boot.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\boot.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC16) : "..\vector\vecttbl.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\vecttbl.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\vector\vecttbl.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC17) : "..\vector\ram_vect.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ram_vect.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\vector\ram_vect.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC18) : "..\app\debug.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\debug.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\debug.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC19) : "..\app\debugprocess.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\debugprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\debugprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC20) : "..\app\allprocess.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\allprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\allprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC21) : "..\app\userprocess.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\userprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\userprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC22) : "..\app\debugdl.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\debugdl.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\debugdl.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC23) : "..\app\btmondl.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\btmondl.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\btmondl.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC24) : "..\app\ymodemrecv.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ymodemrecv.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\ymodemrecv.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC25) : "..\app\storage.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\storage.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\storage.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC26) : "..\cmxwrap\version.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\version.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\version.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC27) : "..\app\loader.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\loader.obj"
-nolist
-speed=register,loop,inline=105
-chgincpath
"..\app\loader.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC28) : "..\app\dtc_vector.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\dtc_vector.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\dtc_vector.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC29) : "..\monitor\msghndl.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\msghndl.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\msghndl.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC30) : "..\monitor\branch.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\branch.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\branch.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC31) : "..\monitor\break.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\break.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\break.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC32) : "..\monitor\control.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\control.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\control.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC33) : "..\monitor\exe.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\exe.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\exe.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC34) : "..\monitor\ilreslv1.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ilreslv1.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\ilreslv1.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC35) : "..\monitor\ilreslv2.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ilreslv2.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\ilreslv2.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC36) : "..\monitor\ilreslv3.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ilreslv3.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\ilreslv3.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC37) : "..\monitor\ilreslv4.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ilreslv4.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\ilreslv4.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC38) : "..\monitor\init.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\init.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\init.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC39) : "..\monitor\instleng.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\instleng.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\instleng.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC40) : "..\monitor\main.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\main.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\main.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC41) : "..\monitor\bptable.c" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\bptable.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\bptable.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC42) : "..\monitor\sci_mon.c"  $(HITACHI_H8SH8300_CC_COMPILER_DEPFILESC42)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\sci_mon.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\monitor\sci_mon.c"
-lang=c
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC43) : "..\serial\ptpprocess.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptpprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\ptpprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC44) : "..\serial\ptplink.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptplink.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\ptplink.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC45) : "..\serial\ptpisr.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptpisr.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\ptpisr.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC46) : "..\serial\intqueue.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\intqueue.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\intqueue.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC47) : "..\serial\memblock.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\memblock.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\memblock.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC48) : "..\serial\memblocklist.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\memblocklist.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\memblocklist.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC49) : "..\serial\memheap.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\memheap.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\memheap.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC50) : "..\serial\crc16.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\crc16.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\crc16.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC51) : "..\serial\dtcsci.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\dtcsci.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\serial\dtcsci.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC52) : "..\download\ptpdnldsend.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptpdnldsend.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\download\ptpdnldsend.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC53) : "..\download\ptpdnldrecv.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptpdnldrecv.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\download\ptpdnldrecv.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC54) : "..\download\ptpdnldprocess.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\ptpdnldprocess.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\download\ptpdnldprocess.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC55) : "..\cmxwrap\mailbox.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\mailbox.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\mailbox.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC56) : "..\app\amd29dl161db.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\amd29dl161db.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\amd29dl161db.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC57) : "..\app\amd29b16.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\amd29b16.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\app\amd29b16.cpp"
-lang=cpp
<<

$(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC58) : "..\cmxwrap\watchdog.cpp" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_CC_COMPILER_EXE) -ws=<<
-cpu=2600a:24
-include="..\h2633f","..\include","..\global","..\cmx","..\cmxwrap","..\serial","..\vector","..\app","..\monitor","..\download"
-define=_NDEBUG=1,RUN_IN_RAM=0,RUN_IN_ROM=1,NDEBUG=1,H8S2623=1,MON_SCI0=1,RAM_START=0x200000
-object="..\release\watchdog.obj"
-nolist
-speed=register,shift,loop,switch,struct,expression,inline=105
-chgincpath
"..\cmxwrap\watchdog.cpp"
-lang=cpp
<<

!MESSAGE
!MESSAGE Executing Hitachi H8S,H8/300 Assembler phase
!MESSAGE

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC0) : "..\cmx\cxsk5ha.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\cmx\cxsk5ha.src"
-cpu=2600a:24
-nodebug
-object="..\release\cxsk5ha.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC1) : "..\cmx\starth8s.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\cmx\starth8s.src"
-cpu=2600a:24
-nodebug
-object="..\release\starth8s.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC2) : "..\monitor\execute.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\monitor\execute.src"
-cpu=2600a:24
-nodebug
-object="..\release\execute.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC3) : "..\monitor\initshv.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\monitor\initshv.src"
-cpu=2600a:24
-nodebug
-object="..\release\initshv.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC4) : "..\monitor\cstartup.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\monitor\cstartup.src"
-cpu=2600a:24
-nodebug
-object="..\release\cstartup.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC5) : "..\monitor\intv.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\monitor\intv.src"
-cpu=2600a:24
-nodebug
-object="..\release\intv.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC6) : "..\monitor\dtc.src" 
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\monitor\dtc.src"
-cpu=2600a:24
-nodebug
-object="..\release\dtc.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC7) : $(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC1)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\release\intprg.src"
-cpu=2600a:24
-include="..\h2633f"
-include="..\include"
-include="..\global"
-include="..\cmx"
-include="..\cmxwrap"
-include="..\serial"
-include="..\vector"
-include="..\app"
-include="..\monitor"
-include="..\download"
-nodebug
-object="..\release\intprg.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC8) : $(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC2)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\release\resetprg.src"
-cpu=2600a:24
-include="..\h2633f"
-include="..\include"
-include="..\global"
-include="..\cmx"
-include="..\cmxwrap"
-include="..\serial"
-include="..\vector"
-include="..\app"
-include="..\monitor"
-include="..\download"
-nodebug
-object="..\release\resetprg.obj"
-nolist
-chgincpath
-errorpath
<<

$(HITACHI_H8SH8300_ASSEMBLER_OUTFILESC9) : $(HITACHI_H8SH8300_CC_COMPILER_OUTFILESC9)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_ASSEMBLER_EXE) -ws=<<
"..\release\asm.src"
-cpu=2600a:24
-include="..\h2633f"
-include="..\include"
-include="..\global"
-include="..\cmx"
-include="..\cmxwrap"
-include="..\serial"
-include="..\vector"
-include="..\app"
-include="..\monitor"
-include="..\download"
-nodebug
-object="..\release\asm.obj"
-nolist
-chgincpath
-errorpath
<<

!MESSAGE
!MESSAGE Executing Hitachi H8S,H8/300 IM OptLinker phase
!MESSAGE

$(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0) : $(HITACHI_H8SH8300_IM_OPTLINKER_INFILESC0)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H8SH8300_IM_OPTLINKER_EXE) -ws=<<
rom (D,R),(DHEAP,RHEAP),(DCMX,RCMX)
print "..\release\Boot.map"
nooptimize
start DVECTTBL,DINTTBL(00),CDTC,PMONITOR,CMONITOR,INTVEC,INTV2,INT_DTC(0400),PResetPRG,PIntPRG,D,C$DSEC,C$BSEC,C$VTBL,DHEAP,DCMX,CResetPRG,C(010000),CBldDate(01FF00),CCheckSum(01FFF8),P(020000),STACK,BBootAPI,BCMX,RCMX,BHEAP(03C0000),BRTC,BMONITOR(0FFB000),BMONFLAG,BResetPRG,RHEAP,BSCI,B,R(0FFB200),S(0FFEBC0)
exclude
udfcheck
check_section
align_section
output "..\release\Boot.abs"
input "..\release\cxsk5ha.obj"
input "..\release\starth8s.obj"
input "..\release\execute.obj"
input "..\release\initshv.obj"
input "..\release\cstartup.obj"
input "..\release\intv.obj"
input "..\release\dtc.obj"
input "..\release\intprg.obj"
input "..\release\resetprg.obj"
input "..\release\asm.obj"
input "..\release\hwsetup.obj"
input "..\release\sbrk.obj"
input "..\release\dbsct.obj"
input "..\release\g_cmx.obj"
input "..\release\resource.obj"
input "..\release\cstart.obj"
input "..\release\cmx_init.obj"
input "..\release\baseprocess.obj"
input "..\release\queue.obj"
input "..\release\rtc.obj"
input "..\release\sci.obj"
input "..\release\timer.obj"
input "..\release\boot.obj"
input "..\release\vecttbl.obj"
input "..\release\ram_vect.obj"
input "..\release\debug.obj"
input "..\release\debugprocess.obj"
input "..\release\allprocess.obj"
input "..\release\userprocess.obj"
input "..\release\debugdl.obj"
input "..\release\btmondl.obj"
input "..\release\ymodemrecv.obj"
input "..\release\storage.obj"
input "..\release\version.obj"
input "..\release\loader.obj"
input "..\release\dtc_vector.obj"
input "..\release\msghndl.obj"
input "..\release\branch.obj"
input "..\release\break.obj"
input "..\release\control.obj"
input "..\release\exe.obj"
input "..\release\ilreslv1.obj"
input "..\release\ilreslv2.obj"
input "..\release\ilreslv3.obj"
input "..\release\ilreslv4.obj"
input "..\release\init.obj"
input "..\release\instleng.obj"
input "..\release\main.obj"
input "..\release\bptable.obj"
input "..\release\sci_mon.obj"
input "..\release\ptpprocess.obj"
input "..\release\ptplink.obj"
input "..\release\ptpisr.obj"
input "..\release\intqueue.obj"
input "..\release\memblock.obj"
input "..\release\memblocklist.obj"
input "..\release\memheap.obj"
input "..\release\crc16.obj"
input "..\release\dtcsci.obj"
input "..\release\ptpdnldsend.obj"
input "..\release\ptpdnldrecv.obj"
input "..\release\ptpdnldprocess.obj"
input "..\release\mailbox.obj"
input "..\release\amd29dl161db.obj"
input "..\release\amd29b16.obj"
input "..\release\watchdog.obj"
library "$(TC_INSTALL_DIR)\lib\c8s26a.lib"
library "c:\cmx\Libhsa.lib"
exit
<<

!MESSAGE
!MESSAGE Executing Hitachi H Series Stype Converter phase
!MESSAGE

$(HITACHI_H_SERIES_STYPE_CONVERTER_OUTFILESC0) : $(HITACHI_H8SH8300_IM_OPTLINKER_OUTFILESC0)
	$(HITACHI_H8SH8300_CC_COMPILER_EXEDIR)\$(HITACHI_H_SERIES_STYPE_CONVERTER_EXE) -ws=<<
"..\release\Boot.abs"
"..\release\Boot.mot"
<<

