/***********************************************************************/
/*                                                                     */
/*  FILE        :vecttbl.c                                             */
/*  DATE        :Wed, May 01, 2002                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :H8S/2633F                                             */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
/*
 * RCS: $Header: vecttbl.c 1.1 2007/12/06 11:39:19PST Zheng Miao (zmiao) Exp  $
 * $Revision: 1.1 $
 *
 */


#include    "vect.h" 
#include 	"ConstDef.h"
//#include 	"project.h"

#ifndef RAM_START
#define RAM_START (0x200000)
#endif

// From Monitor module (Zheng Miao 2/12/2003)
extern void NMIcapture(void);
extern void BreakPoint(void);
		
#pragma section VECTTBL
void *RESET_Vectors[] = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset
#if RUN_IN_RAM 
	// Debug version
	((char *) PowerON_Reset) + JUMP_INSTR, 
#else  
	// Release version
	((char *) PowerON_Reset), 
#endif	                                                                                                                          
//;<<VECTOR DATA END (POWER ON RESET)>>
//;<<VECTOR DATA START (MANUAL RESET)>>
//;1 Manual Reset 
#if RUN_IN_RAM
	((char *) Manual_Reset) + JUMP_INSTR
#else   
	// Release version
	(void *)(0x200004)
#endif	
//;<<VECTOR DATA END (MANUAL RESET)>>
};

#if RUN_IN_RAM	    
#pragma section VECTTBL_C
void *RESET_Vectors_C[] = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset
#if RUN_IN_RAM 
	// Debug version
	((char *) PowerON_Reset) + JUMP_INSTR, 
#else  
	// Release version
	((char *) PowerON_Reset), 
#endif	                                                                                                                          
//;<<VECTOR DATA END (POWER ON RESET)>>
//;<<VECTOR DATA START (MANUAL RESET)>>
//;1 Manual Reset 
#if RUN_IN_RAM
	((char *) Manual_Reset) + JUMP_INSTR
#else   
	// Release version
	(void *)(0x200004)
#endif		                                                                                                                           
//;<<VECTOR DATA END (MANUAL RESET)>>
};
#endif // RUN_IN_RAM

#pragma section INTTBL

#if RUN_IN_RAM  
void *INT_Vectors[] = 
#include "IntrList.h"
#endif  
              
#if RUN_IN_ROM                          

//#if IGNORE_RAM
//#undef JUMP_INSTR
//#define JUMP_INSTR 0  
//void *INT_Vectors[] = 
//#include "IntrList.h"
//#else 
#include "JumpList.h"
//#endif

#endif		
